# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
    icon: fa-home
  - name: Crafts & Details
    url: docs/
    weight: 20
  - name: Blog
    url: blog/
    weight: 30
  - name: Work Experiance
    url: showcase/
    weight: 40
  - name: Time Lapse
    url: community/
    weight: 50

sidebar:
  - identifier: more
    name: "BK V1 ↗"
    url: "https://perwebk-portfolio.pages.dev/"
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "For Fun"
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyvoGgW3OZt2qdMC9cEOI0Yvn346FQaSHgLz4wjKra8fI-CQmgKjGoBqJmc_2nk7yXbmA&usqp=CAU"
    weight: 3
